# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7575b35b492fc619524c03b7a1b33425214040a5bbe82398a19117af90fae3016033f5b18631cbb09293a4f81ec60a38f1a6793bcf284969baeb0d14ea66bc3f

test:
  secret_key_base: f2380936f538f7f6e9fa515816f0c86dc1f4aa08a3298de27a952024878ee5350be08dda181dd12e7d2acc02b3b58d30a7389419fbf441c91cfac5e7ec40316e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
